---

:development: &defaults
  :adapter: sqlite3
  :database: ../../data/wistle/dev.db

:test:
  <<: *defaults
  :database: ../../data/wistle/test.db

:production:
  <<: *defaults
  :database: /u/data/fs/wistle/pro.db
